name: search_diseases
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  package_info_plus: ^1.4.3+1
  easy_localization: 3.0.1
  logger: ^1.1.0
  flutter_tags_x: ^1.1.0
  flutter_modular: ^5.0.3
  hexcolor: ^2.0.7
  flutter_svg: ^1.0.3
  string_validator: ^0.3.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  connectivity_plus: ^3.0.2
  animated_svg: ^1.1.2
  url_launcher: ^6.1.6
  cached_network_image: ^3.2.3
  chewie: ^1.3.6
  lottie: ^2.2.0
  video_player: ^2.4.8
  flutter_holo_date_picker: ^1.1.0
  reading_time: ^2.0.0
  card_swiper: ^2.0.4
  smooth_page_indicator: ^1.0.0+2
  auto_animated: ^3.1.0
  device_info_plus: ^8.0.0
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  flutter_keyboard_visibility: ^5.4.0
  expandable: ^5.0.1
  flutter_linkify: ^5.0.2
  flutter_staggered_grid_view: ^0.6.2
  flutter_parsed_text: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.0.3+2
  json_serializable: ^6.4.0
  hive_generator: ^2.0.0
  build_runner: ^2.2.1
  aligned_dialog: ^0.0.6

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
